[[pages]]
path = "/"
screenshotTimestamp = "2026-06-03T06:01:31Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/e58a08b4-1292-4bc4-adbb-b055a04c4a15/dcc33eb4-e902-46b7-8d0d-d9660827aa53/giwAtI4"

[[pages]]
path = "/settings"
screenshotTimestamp = "2026-06-03T06:20:11Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/e58a08b4-1292-4bc4-adbb-b055a04c4a15/dcc33eb4-e902-46b7-8d0d-d9660827aa53/o5TeutP"
